development:
  from: no-reply@imt.sample
  address: address
  port: 587
  enable_starttls_auto: true
  authentication: plain
  user_name: username
  password: password

production:
    from: no-reply@imt.sample
    address: address
    port: 587
    enable_starttls_auto: true
    authentication: plain
    user_name: username
    password: password
